server:
  port: 8085

logging:
  level:
    orgspringframework: DEBUG
    com.example.demo: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb?allowPublicKeyRetrieval=true&useSSL=false
    # url: jdbc:mysql://${DB_HOST:dis_db}:${DB_PORT:3306}/testdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# App Properties
demo:
  password:
    resetTokenExpire: 24 # hours
    updateUrl: ~/auth/update-password/
  email:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000