server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb?allowPublicKeyRetrieval=true&useSSL=false
    # url: jdbc:mysql://${DB_HOST:dis_db}:${DB_PORT:3306}/testdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000